version: '3'
services:
  recipe-book-datastore:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./datastore/migrations/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  recipe-book-api:
    build:
      context: ./api
    environment:
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      DATABASE_NAME: db
      DATABASE_PORT: 5432
      DATABASE_HOST: recipe-book-datastore
    ports:
      - "3080:3080"
    container_name: recipe-book-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
    depends_on:
      - recipe-book-datastore

  recipe-book-ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    container_name: recipe-book-ui
    stdin_open: true
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules
    depends_on:
      - recipe-book-api

######## Other containers #########